theme: minima
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  poem:
    output: true
  code:
    output: true

defaults:
  - scope:
      path: ""
      type: "poem"
    values:
      layout: "poem"
  - scope:
      path: ""
      type: "code"
    values:
      layout: "poem"