theme: minima
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  poem:
    output: true

defaults:
  - scope:
      path: "./_pome"
      type: "poem"
    values:
      layout: "poem"