theme: minima
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  poem:
    output: true
  CppCon:
    output: true
  Cpp:
    output: true

defaults:
  - scope:
      path: ""
      type: "poem"
    values:
      layout: "poem"
  - scope:
      path: ""
      type: "CppCon"
    values:
      layout: "poem"
  - scope:
      path: ""
      type: "Cpp"
    values:
      layout: "poem"