# theme: minima
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:year/:month/:day/:title:output_ext

minimal_mistakes_skin: default
search: true

include:
  - _pages

collections:
  poem:
    output: true
  code:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      related: true
  - scope:
      path: ""
      type: "poem"
    values:
      layout: single
  - scope:
      path: ""
      type: "code"
    values:
      layout: single
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
